export type {
  AboutInfo,
  AcceptedEventTrendPoint,
  AppBehaviorSettings,
  DataStorageInfo,
  ExtensionCapabilities,
  ExclusionsSettings,
  ExtensionEffectiveSettings,
  ExtensionHandshakeRequest,
  ExtensionHandshakeResponse,
  ExtensionProtocolLimits,
  ExtensionSettings,
  ExtensionStatus,
  GeneralSettings,
  MachineFreshnessBucket,
  PrivacySettings,
  ReliabilityKpiSummary,
  SettingsData,
  SyncLatencyStats,
  SystemInfo,
  TrackingCoverageGap,
  TrackingSettings,
} from './types';
