// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';

export function GetAnalyticsData(arg1:string):Promise<contracts.AnalyticsData>;

export function GetCalendarDayData(arg1:string):Promise<contracts.CalendarDayData>;

export function GetCalendarMonthData(arg1:string):Promise<contracts.CalendarMonthData>;

export function GetExtensionStatus():Promise<contracts.ExtensionStatus>;

export function GetIngestionStats():Promise<contracts.IngestionStats>;

export function GetOverviewData():Promise<contracts.OverviewData>;

export function GetProjectsPageData(arg1:string):Promise<contracts.ProjectsPageData>;

export function GetSessionsPageData(arg1:string):Promise<contracts.SessionsPageData>;

export function GetSettingsData():Promise<contracts.SettingsData>;

export function GetSystemInfo():Promise<contracts.SystemInfo>;

export function IngestEvents(arg1:contracts.IngestEventsRequest):Promise<contracts.IngestEventsResponse>;

export function ListKnownMachines():Promise<Array<contracts.MachineInfo>>;

export function ListRecentEvents(arg1:number):Promise<Array<contracts.ActivityEvent>>;

export function Ping():Promise<string>;

export function UpdateSettingsData(arg1:contracts.SettingsData):Promise<contracts.SettingsData>;
