// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnalyticsData(arg1) {
  return window['go']['main']['App']['GetAnalyticsData'](arg1);
}

export function GetCalendarDayData(arg1) {
  return window['go']['main']['App']['GetCalendarDayData'](arg1);
}

export function GetCalendarMonthData(arg1) {
  return window['go']['main']['App']['GetCalendarMonthData'](arg1);
}

export function GetExtensionStatus() {
  return window['go']['main']['App']['GetExtensionStatus']();
}

export function GetIngestionStats() {
  return window['go']['main']['App']['GetIngestionStats']();
}

export function GetMigrationStatus() {
  return window['go']['main']['App']['GetMigrationStatus']();
}

export function GetOverviewData() {
  return window['go']['main']['App']['GetOverviewData']();
}

export function GetProjectsPageData(arg1) {
  return window['go']['main']['App']['GetProjectsPageData'](arg1);
}

export function GetSessionsPageData(arg1) {
  return window['go']['main']['App']['GetSessionsPageData'](arg1);
}

export function GetSettingsData() {
  return window['go']['main']['App']['GetSettingsData']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function IngestEvents(arg1) {
  return window['go']['main']['App']['IngestEvents'](arg1);
}

export function ListKnownMachines() {
  return window['go']['main']['App']['ListKnownMachines']();
}

export function ListRecentEvents(arg1) {
  return window['go']['main']['App']['ListRecentEvents'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function UpdateSettingsData(arg1) {
  return window['go']['main']['App']['UpdateSettingsData'](arg1);
}
