// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnalyticsData(arg1) {
  return window['go']['main']['App']['GetAnalyticsData'](arg1);
}

export function GetAutostartRegistrationStatus() {
  return window['go']['main']['App']['GetAutostartRegistrationStatus']();
}

export function GetCalendarDayData(arg1) {
  return window['go']['main']['App']['GetCalendarDayData'](arg1);
}

export function GetCalendarMonthData(arg1) {
  return window['go']['main']['App']['GetCalendarMonthData'](arg1);
}

export function GetExtensionEffectiveSettings() {
  return window['go']['main']['App']['GetExtensionEffectiveSettings']();
}

export function GetExtensionStatus() {
  return window['go']['main']['App']['GetExtensionStatus']();
}

export function GetIngestionStats() {
  return window['go']['main']['App']['GetIngestionStats']();
}

export function GetMigrationStatus() {
  return window['go']['main']['App']['GetMigrationStatus']();
}

export function GetOverviewData() {
  return window['go']['main']['App']['GetOverviewData']();
}

export function GetProjectsPageData(arg1) {
  return window['go']['main']['App']['GetProjectsPageData'](arg1);
}

export function GetSessionStatsForRange(arg1, arg2) {
  return window['go']['main']['App']['GetSessionStatsForRange'](arg1, arg2);
}

export function GetSessionsPageData(arg1) {
  return window['go']['main']['App']['GetSessionsPageData'](arg1);
}

export function GetSettingsData() {
  return window['go']['main']['App']['GetSettingsData']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetVSCodeBridgeHealth() {
  return window['go']['main']['App']['GetVSCodeBridgeHealth']();
}

export function IngestEvents(arg1) {
  return window['go']['main']['App']['IngestEvents'](arg1);
}

export function ListKnownMachines() {
  return window['go']['main']['App']['ListKnownMachines']();
}

export function ListRecentEvents(arg1) {
  return window['go']['main']['App']['ListRecentEvents'](arg1);
}

export function ListRecentSessions(arg1) {
  return window['go']['main']['App']['ListRecentSessions'](arg1);
}

export function ListSessionsForDate(arg1) {
  return window['go']['main']['App']['ListSessionsForDate'](arg1);
}

export function ListSessionsForRange(arg1, arg2) {
  return window['go']['main']['App']['ListSessionsForRange'](arg1, arg2);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RebuildAllSessions() {
  return window['go']['main']['App']['RebuildAllSessions']();
}

export function RebuildSessionsForDate(arg1) {
  return window['go']['main']['App']['RebuildSessionsForDate'](arg1);
}

export function RebuildSessionsForRange(arg1, arg2) {
  return window['go']['main']['App']['RebuildSessionsForRange'](arg1, arg2);
}

export function ReconnectVSCodeExtension() {
  return window['go']['main']['App']['ReconnectVSCodeExtension']();
}

export function RefreshVSCodeExtensionStatus() {
  return window['go']['main']['App']['RefreshVSCodeExtensionStatus']();
}

export function ResetSettingsSection(arg1) {
  return window['go']['main']['App']['ResetSettingsSection'](arg1);
}

export function UpdateAppBehaviorSettings(arg1) {
  return window['go']['main']['App']['UpdateAppBehaviorSettings'](arg1);
}

export function UpdateExclusionsSettings(arg1) {
  return window['go']['main']['App']['UpdateExclusionsSettings'](arg1);
}

export function UpdateExtensionSettings(arg1) {
  return window['go']['main']['App']['UpdateExtensionSettings'](arg1);
}

export function UpdateGeneralSettings(arg1) {
  return window['go']['main']['App']['UpdateGeneralSettings'](arg1);
}

export function UpdatePrivacySettings(arg1) {
  return window['go']['main']['App']['UpdatePrivacySettings'](arg1);
}

export function UpdateSettingsData(arg1) {
  return window['go']['main']['App']['UpdateSettingsData'](arg1);
}

export function UpdateTrackingSettings(arg1) {
  return window['go']['main']['App']['UpdateTrackingSettings'](arg1);
}
