export function extname(path: string): string {
  const dot = path.lastIndexOf('.');
  const slash = Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\'));
  return dot > slash && dot !== -1 ? path.slice(dot) : '';
}

// Maps file extensions to language IDs consistent with the VS Code extension.
const extToLanguage: Record<string, string> = {
  '.ts': 'typescript',
  '.tsx': 'typescriptreact',
  '.js': 'javascript',
  '.jsx': 'javascriptreact',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.go': 'go',
  '.rs': 'rust',
  '.py': 'python',
  '.rb': 'ruby',
  '.java': 'java',
  '.kt': 'kotlin',
  '.swift': 'swift',
  '.c': 'c',
  '.cc': 'cpp',
  '.cpp': 'cpp',
  '.cxx': 'cpp',
  '.h': 'c',
  '.hpp': 'cpp',
  '.cs': 'csharp',
  '.php': 'php',
  '.html': 'html',
  '.htm': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.less': 'less',
  '.json': 'json',
  '.jsonc': 'jsonc',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.md': 'markdown',
  '.mdx': 'mdx',
  '.sh': 'shellscript',
  '.bash': 'shellscript',
  '.zsh': 'shellscript',
  '.fish': 'shellscript',
  '.lua': 'lua',
  '.vim': 'vim',
  '.sql': 'sql',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.tf': 'terraform',
  '.tfvars': 'terraform',
  '.proto': 'protobuf',
  '.dart': 'dart',
  '.elm': 'elm',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.hs': 'haskell',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.clj': 'clojure',
  '.cljs': 'clojurescript',
  '.r': 'r',
  '.R': 'r',
  '.scala': 'scala',
  '.nix': 'nix',
  '.zig': 'zig',
};

export function languageFromExtension(ext: string): string {
  return extToLanguage[ext] ?? 'unknown';
}
